# Generated by Django 5.0.6 on 2024-05-22 20:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardiovascularsymptom',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='chroniccondition',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='currentmedication',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='familymedicalhistory',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='gastrointestinalsymptom',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='generalsymptom',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='lifestylehabit',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='musculoskeletalsymptom',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='neurologicalsymptom',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='pastsurgeryorhospitalization',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='respiratorysymptom',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='skinsymptom',
            name='patient',
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('doctor', models.CharField(max_length=150)),
                ('notes', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('amount', models.FloatField()),
                ('notes', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='Allergy',
        ),
        migrations.DeleteModel(
            name='CardiovascularSymptom',
        ),
        migrations.DeleteModel(
            name='ChronicCondition',
        ),
        migrations.DeleteModel(
            name='CurrentMedication',
        ),
        migrations.DeleteModel(
            name='FamilyMedicalHistory',
        ),
        migrations.DeleteModel(
            name='GastrointestinalSymptom',
        ),
        migrations.DeleteModel(
            name='GeneralSymptom',
        ),
        migrations.DeleteModel(
            name='LifestyleHabit',
        ),
        migrations.DeleteModel(
            name='MusculoskeletalSymptom',
        ),
        migrations.DeleteModel(
            name='NeurologicalSymptom',
        ),
        migrations.DeleteModel(
            name='PastSurgeryOrHospitalization',
        ),
        migrations.DeleteModel(
            name='RespiratorySymptom',
        ),
        migrations.DeleteModel(
            name='SkinSymptom',
        ),
    ]
